begin
  require 'nanoc3/tasks'
rescue LoadError
  require 'rubygems'
  require 'nanoc3/tasks'
end

desc "Build the site"
task :build do
  sh "nanoc compile"
end

desc "Remove output files generated by nanoc3"
task :clean do
  sh "rm -rf public/*"
end
